export const selectionMeetingPlaces = [
  "meeting Room Ground Floor 1",
  "meeting Room Ground Floor 2",
  "meeting Room Ground Floor 3",
  "meeting Room Ground Floor 4",
  "meeting Room Ground Floor 5",
  "meeting Room Ground Floor 6",
  "meeting Room Ground Floor 7",
  "meeting Room Ground Floor 8",
  "meeting Room Ground Floor 9",
  "meeting Room Basement Floor 1",
  "meeting Room Basement Floor 2",
  "meeting Room Basement Floor 3",
  "meeting Room Basement Floor 4",
  "meeting Room Basement Floor 5",
  "meeting Room Basement Floor 6",
  "meeting Room Basement Floor 7",
  "meeting Room Basement Floor 8",
];

export const selectionProgram = [
  "The Garage employee",
  "The Garage Plus",
  "The Garage incubator",
  "Boost",
  "Antler",
  "Sunbolah",
  "Taqadam",
  "Sparks Lap",
  "SEA",
  "Game pioneers",
];
